version: "3"

services:
  nats-server:
    image: nats:2.10
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    depends_on:
      - nats-server
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build: ./auth-ms
    depends_on:
      - nats-server
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${AUTH_MS_JWT_SECRET}

  products-ms:
    build: ./products-ms
    depends_on:
      - nats-server
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  payments-ms:
    build: ./payments-ms
    depends_on:
      - nats-server
    ports:
      - "${PAYMENTS_MS_PORT}:3003"
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_KEY=${PAYMENTS_STRIPE_KEY}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_STRIPE_CANCEL_URL}

  orders-ms:
    build: ./orders-ms
    depends_on:
      - nats-server
      - orders-db
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - PRODUCTS_MICROSERVICE_HOST=${PRODUCTS_MICROSERVICE_HOST}
      - PRODUCTS_MICROSERVICE_PORT=${PRODUCTS_MICROSERVICE_PORT}

  orders-db:
    image: 'postgres:16.2'
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  

