apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-west2-docker.pkg.dev/custom-woodland-448200-m5/store-microservices/payments-ms
        name: payments-ms
        env: 
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: payments-ms-secrets
                key: stripeKey
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom: 
              secretKeyRef:
                name: payments-ms-secrets
                key: stripeEndpointSecret
          - name: STRIPE_SUCCESS_URL
            value: "http://localhost:3003/payments/success"
          - name: STRIPE_CANCEL_URL
            value: "http://localhost:3003/payments/cancel"
        resources: {}
status: {}
